# Generated by Django 4.2.24 on 2025-10-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0291_alter_logentry_object_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemDBEventConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("issue_coupons", models.BooleanField(default=False)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dbevent_item",
                        to="pretixbase.item",
                    ),
                ),
            ],
        ),
    ]
